### ISSUE TITLE
Unable to add listener on item click

### ISSUE THREAD

**Issue by pandeyVishakha** [adef145/SpinningWheelAndroid#1]
Hi,

I just want to add listener on item click since each item had drawn via canvas so we can not add listener directly on canvas.
So I had tried to add a custom view inside onDraw(Canvas canvas) but getting some error .
@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        if (circle == null) {
            initCircle();
        }

        if (hasData() && (points == null || points.length != getItemSize())) {
            initPoints();
        }

        drawCircle(canvas);

        drawWheel(canvas);

        ]drawWheelItems(canvas);
drawTriangle(canvas);
    }

Can you help me in adding listener to item click?

I have to open a popup on item click.

**Comment by adef145** [comment]
Sorry for late response..

Can you use method like `getSelectedItem`?

Basically, you get point user click, and match each item on the wheel
